<?php
defined('BASEPATH') OR exit('No direct script access allowed');

class Email extends CI_Controller{

    
    function send($id,$unhashedpassword){


		$user = $this->User_Model->get_user_with_id($id);
//			print "<pre>";
//			echo var_dump($user->username);
//			print "</pre>";
//			die('here');
		// Load PHPMailer library
        $this->load->library('phpmailer_lib');

        // PHPMailer object
        $mail = $this->phpmailer_lib->load();

        // SMTP configuration
        $mail->isSMTP();
        $mail->Host     = 'smtp.mailtrap.io';
        $mail->SMTPAuth = true;
        $mail->Username = '161132fe15962d';
        $mail->Password = 'cec49040009350';
        $mail->SMTPSecure = '';
        $mail->Port = 2525;

        $mail->setFrom('noreply@trusted-components.com', 'TrustedComponent');
//        $mail->addReplyTo('info@example.com', 'CodexWorld');
        
        // Add a recipient
        $mail->addAddress($user->email);
        
        // Add cc or bcc 
       //$mail->addCC('cc@example.com');
       // $mail->addBCC('bcc@example.com');
        
        // Email subject
        $mail->Subject = 'Thank You For Registering ';

        // Set email format to HTML
        $mail->isHTML(true);
        $href= site_url('login');
        // Email body content
        $mailContent = "<br>
<h3>Dear $user->username,</h3>
<h4>Here is your account details . Please do not lose them.</h4><br>
<h4> Email: $user->email</h4><br>
<h4> Password: $unhashedpassword</h4> <br>
<h4>You can log in at: <a class='btn btn-dark' href='$href'>Log-In</a></h4><br>
<p>This is an autogenerated email, do not reply.</p><br><br>
<b>Thanks,</b><br>
<b>TrustedComponents Team</b>
<br>
";
        $mail->Body = $mailContent;
        // Send email
        if(!$mail->send()){
            echo 'Message could not be sent.';
            echo 'Mailer Error: ' . $mail->ErrorInfo;
        }else{
			$this->session->set_flashdata('success','Registration Successful, Please log-in to your account.');
			redirect('login');
        }
    }
    
}
